server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/result
    min-response-size: 1024
  servlet:
    session:
      timeout: 1800
spring:
  data:
    mongodb:
      host: cooggo.com
      port: 27017
      database: match
#  data.mongodb.uri: mongodb://mongoadmin:mongoadmin@cooggo.com:27017/test
# log
logging:
  config: classpath:logback-test.xml
