# Tomcat settings
server:
  port: 9090
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/result
    min-response-size: 1024
  servlet:
    session:
      timeout: 1800

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      incarcloud: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}

# Incarcloud settings
incarcloud:
  swagger2:
    api:
      title: 英卡数据流竞赛在线API文档
      description: 本文档包含该项目全部业务接口，注意保密。
      service-url: http://localhost:8080/doc.html
      version: 0.1.0-SNAPSHOT

# Spring settings
spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:cooggo.com}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: match
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false  #是否使用缓存
    mode: HTML5
    suffix: .html
